# Generated by Django 3.2.9 on 2021-11-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_receipts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='org_number',
            new_name='phone',
        ),
    ]
