# Generated by Django 3.2.9 on 2021-12-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_receipts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
